services:
  - type: web
    name: soccer-visualizer
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_KEY
        value: 64fce2370ab54345b892c429472e3845
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    healthCheckPath: /api/health
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 